#!/bin/bash
SCRIPT_DIR=$(pwd)
cd "$SCRIPT_DIR/build" || { echo "Error: Build directory not found."; exit 1; }
echo "------ Compiling code ------"
if ! cmake ..; then
    echo "Error: CMake configuration failed."
    exit 1
fi
if ! make; then
    echo "Error: Compilation failed."
    exit 1
fi

echo "***** Running code *****"
if ! ./OpenGLProject; then
    echo "Error: Execution failed."
    exit 1
fi

cd "$SCRIPT_DIR" || { echo "Error: Unable to return to the original directory."; exit 1; }
